### PR TITLE
[Breaking Change] Update for TailwindCSS v1.0.0

### PR DESCRIPTION
**Pull request by akoepcke**
Fixes the config path to reflect TailwindCSS v1.0.0 new config file structure.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@markhuot Any chance of getting this landed?

**Comment by markhuot** [comment]
Yup, as soon as Tailwind releases 1.0.0 I'll get this merged. I'm hesitant to merge it today because then it won't work with the current stable release.

**Comment by danielbachhuber** [comment]
> I'm hesitant to merge it today because then it won't work with the current stable release.

Oh, good point. Wouldn't tagging a `2.0.0` with this breaking change be sufficient though?

**Comment by markhuot** [comment]
I don't think so because it'd still break today with `npm i -D tailwindcss tailwindcss-owl`.

**Comment by markhuot** [comment]
FYI, this is now available under `npm i --save tailwindcss-owl@next`

**Comment by danielbachhuber** [comment]
Thanks @markhuot — works great!

**Pull request merged**
